version: '3.1'

services:

  wordpress:
    build:
      context: .
    ports:
      - 8080:80
    restart: always
    environment:
      WORDPRESS_DB_PASSWORD: dUYSm9c4
      WORDPRESS_CONFIG_EXTRA: |
        @ini_set( 'upload_max_filesize' , '128M' );
        @ini_set( 'post_max_size', '128M');
        @ini_set( 'memory_limit', '256M' );
    volumes:
      - ./src:/var/www/html/wp-content/themes/ctlm

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dUYSm9c4
      MYSQL_DATABASE: wordpress
